### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 8: invalid start byte

### ISSUE THREAD

**Issue by chxx2277** [DannyCork/python-whois#100]
import whois
domain = whois.query('baidu.com')
print(domain.name)

error:
Traceback (most recent call last):
  File "C:/Users/chen/PycharmProjects/little-project/checkip.py", line 36, in <module>
    domain = whois.query('baidu.com')
  File "C:\Users\chen\AppData\Local\Programs\Python\Python38\lib\site-packages\whois\__init__.py", line 63, in query
    pd = do_parse(do_query(d, force, cache_file, slow_down, ignore_returncode), tld)
  File "C:\Users\chen\AppData\Local\Programs\Python\Python38\lib\site-packages\whois\_1_query.py", line 46, in do_query
    _do_whois_query(dl, ignore_returncode),
  File "C:\Users\chen\AppData\Local\Programs\Python\Python38\lib\site-packages\whois\_1_query.py", line 62, in _do_whois_query
    r = r.decode() if PYTHON_VERSION == 3 else r
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 8: invalid start byte.

thank you ~

**Comment by davelytollis** [comment]
I have the same issue.  I have a Korean version of Windows.  To get the install to work I had to modify the setup file and modify this line to  long_description=open('README',encoding='utf-8').read() 
I installed the whois service as described in another thread.  

Now I'm faced with the following

import whois

whois.query('www.google.com')
Traceback (most recent call last):

  File "<ipython-input-2-03dcff8d3b2d>", line 1, in <module>
    whois.query('www.google.com')

  File "C:\Users\dl109403\Anaconda3\lib\site-packages\whois\__init__.py", line 69, in query
    pd = do_parse(do_query(d, force, cache_file, slow_down, ignore_returncode), tld)

  File "C:\Users\dl109403\Anaconda3\lib\site-packages\whois\_1_query.py", line 46, in do_query
    _do_whois_query(dl, ignore_returncode),

  File "C:\Users\dl109403\Anaconda3\lib\site-packages\whois\_1_query.py", line 62, in _do_whois_query
    r = r.decode() if PYTHON_VERSION == 3 else r

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by NanWuIT** [comment]
Same issue here, I am using a Chinese version of Windows, and when I tried to use the whois.query('microsoft.com'), I got the error code: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda\lib\site-packages\whois\__init__.py", line 67, in query
    pd = do_parse(do_query(d, force, cache_file, slow_down, ignore_returncode), tld)
  File "D:\Anaconda\lib\site-packages\whois\_1_query.py", line 46, in do_query
    _do_whois_query(dl, ignore_returncode),
  File "D:\Anaconda\lib\site-packages\whois\_1_query.py", line 62, in _do_whois_query
    r = r.decode() if PYTHON_VERSION == 3 else r
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 8: invalid start byte

**Comment by NanWuIT** [comment]
OK, for me, the solution is go to the management of language, and change the language for non-unicode language to English.
