### ISSUE TITLE
    self._execute_child(args, executable, preexec_fn, close_fds,   File "C:\Program Files (x86)\Python38-32\lib\subprocess.py", line 1307, in _execute_child

### ISSUE THREAD

**Issue by Bishwas-py** [DannyCork/python-whois#103]
>>> domain = whois.query('google.com')
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    domain = whois.query('google.com')
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\whois\__init__.py", line 67, in query
    pd = do_parse(do_query(d, force, cache_file, slow_down, ignore_returncode), tld)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\whois\_1_query.py", line 46, in do_query
    _do_whois_query(dl, ignore_returncode),
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\whois\_1_query.py", line 60, in _do_whois_query
    p = subprocess.Popen(['whois', '.'.join(dl)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "C:\Program Files (x86)\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files (x86)\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by lepythoner** [comment]
same bruh
I think its cause you need linux

**Comment by fhightower** [comment]
There is more discussion about this issue in #123 .
