### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by omijhv** [DannyCork/python-whois#105]
File "c:\python\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by needlesky** [comment]
I also get the same error. Module doen't for on python 3.8.2?

**Comment by DannyCork** [comment]
What's happening here ?
please post example code!

**Comment by needlesky** [comment]
`import whois

print(whois.query('google.com'))`

output:

`Traceback (most recent call last):
  File "C:/Users/Master/Desktop/python_projects/006_whoistutorial/whoisfile.py", line 3, in <module>
    print(whois.query('google.com'))
  File "C:\Python\Python38\lib\site-packages\whois\__init__.py", line 67, in query
    pd = do_parse(do_query(d, force, cache_file, slow_down, ignore_returncode), tld)
  File "C:\Python\Python38\lib\site-packages\whois\_1_query.py", line 46, in do_query
    _do_whois_query(dl, ignore_returncode),
  File "C:\Python\Python38\lib\site-packages\whois\_1_query.py", line 60, in _do_whois_query
    p = subprocess.Popen(['whois', '.'.join(dl)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "C:\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Process finished with exit code 1`

**Comment by JustAPhrog** [comment]
I have same error on win10.

**Comment by fhightower** [comment]
There is more discussion about this issue in #123 .
