### ISSUE TITLE
whois.query not working getting error (FileNotFoundError: [Errno 2] No such file or directory: 'whois')

### ISSUE THREAD

**Issue by qasidali1** [DannyCork/python-whois#224]
Using Ubuntu 20.04

I got the above error when ever I run the code. 

**import whois
domain = whois.query('google.com')
print(domain)**

Code is above.
I have installed whois using 
pip install whois 

Here is the full error

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    domain = whois.query('google.com')
  File "/home/qasid/Python/venv/lib/python3.8/site-packages/whois/__init__.py", line 206, in query
    q = do_query(
  File "/home/qasid/Python/venv/lib/python3.8/site-packages/whois/_1_query.py", line 62, in do_query
    _do_whois_query(
  File "/home/qasid/Python/venv/lib/python3.8/site-packages/whois/_1_query.py", line 119, in _do_whois_query
    p = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'whois'

**Comment by maarten-boot** [comment]
Most likely whois is not installed as it is not a mandatiry requirement
fir the os itself.

Please install whois cli according to e.g.
https://devmanuals.net/install/ubuntu/ubuntu-20-04-focal-fossa/installing-whois-on-ubuntu20-04.html
