### ISSUE TITLE
when query "lg.com" got error 

### ISSUE THREAD

**Issue by baigreen** [DannyCork/python-whois#260]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/whois/__init__.py", line 245, in query
    whois_str = do_query(
  File "/usr/local/lib/python3.8/dist-packages/whois/_1_query.py", line 65, in do_query
    _do_whois_query(
  File "/usr/local/lib/python3.8/dist-packages/whois/_1_query.py", line 173, in _do_whois_query
    raise WhoisCommandFailed(r)
whois.exceptions.WhoisCommandFailed:    Domain Name: LG.COM

**Comment by maarten-boot** [comment]
i see what you mean meta.com returns all info ok, lg.com returns None, but the cli output of whois "lg.com" looks normal
i actually dont get a error but None
i will investigate
```
pip install whois
python3
Python 3.11.1 (main, Jan  6 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
d = whois.query("lg.com", verbose=True, include_raw_whois_text=True)
['lg', 'com']
we have com
com ['lg', 'com']
>>> print (d.__dict__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute '__dict__'. Did you mean: '__dir__'?

```

**Comment by maarten-boot** [comment]
ok found this one: the normal .com tld has a regex for "Domain Name:" while this domain responds with "Domain Name :" 
that was not matched so the library does not see the domain in the output, i changed the regex to "Domain Name\s*:\s*" now it works.

```
python3
Python 3.11.1 (main, Jan  6 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
>>> d = whois.query(domain="lg.com", verbose=True)
['lg', 'com']
we have com
com ['lg', 'com']
force = False
['whois', 'lg.com']
[Querying whois.verisign-grs.com]
[Redirected to whois.whois.co.kr]
[Querying whois.whois.co.kr]
[whois.whois.co.kr]
Domain Name : lg.com
Registry Domain ID: 4980211_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.whois.co.kr
Registrar URL: http://www.whois.co.kr
Updated Date: 2017-06-10T16:10:03Z
Creation Date: 1995-06-08T04:00:00Z
Registrar Registration Expiration Date: 2027-06-07T04:00:00Z
Registrar: Whois Corp.
Registrar IANA ID: 100
Registrar Abuse Contact Email: abuse@whois.co.kr
Registrar Abuse Contact Phone: +82.15884259
Reseller: 
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
Registry Registrant ID: 
Registrant Name: LG Corp.
Registrant Organization: LG Corp.
Registrant Street: LG Twintower 20, Youido-dong, Youngdeungpo-gu,
Registrant City: Seoul
Registrant State/Province: 
Registrant Postal Code: 150721
Registrant Country: KR
Registrant Phone: +82.237732322
Registrant Phone Ext: 
Registrant Fax: 
Registrant Fax Ext: 
Registrant Email: young@lg.com
Registry Admin ID: 
Admin Name: Domain-Manager
Admin Organization: Domain-Manager
Admin Street: LG Twintower 20, Youido-dong, Youngdeungpo-gu,
Admin City: Seoul
Admin State/Province: 
Admin Postal Code: 150721
Admin Country: KR
Admin Phone: +82.237732322
Admin Phone Ext: 
Admin Fax: 
Admin Fax Ext: 
Admin Email: young@lg.com
Registry Tech ID: 
Tech Name: Domain-Manager
Tech Organization: Domain-Manager
Tech Street: LG Twintower 20 Youido-dong Youngdeungpo-gu
Tech City: Seoul
Tech State/Province: 
Tech Postal Code: 150721
Tech Country: KR
Tech Phone: +82.237732322
Tech Phone Ext: 
Tech Fax: 
Tech Fax Ext: 
Tech Email: young@lg.com
Name Server: SECNS.LG.CO.KR
Name Server: PRMNS.LG.CO.KR
DNSSEC: unsigned
URL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/
>>> Last update of WHOIS database: 2023-01-30T18:41:58Z <<<

For more information on Whois status codes, please visit https://icann.org/epp

>>> print(d)
<whois._3_adjust.Domain object at 0x7fae1a7ecf10>
>>> print(d.__dict__)
{'name': 'lg.com', 'tld': 'com', 'registrar': 'Whois Corp.', 'registrant_country': 'KR', 'creation_date': datetime.datetime(1995, 6, 8, 4, 0), 'expiration_date': None, 'last_updated': datetime.datetime(2017, 6, 10, 16, 10, 3), 'status': 'clientTransferProhibited https://icann.org/epp#clientTransferProhibited', 'statuses': ['clientTransferProhibited https://icann.org/epp#clientTransferProhibited', 'clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited'], 'dnssec': False, 'name_servers': ['prmns.lg.co.kr', 'secns.lg.co.kr'], 'registrant': 'LG Corp.', 'emails': ['abuse@whois.co.kr', 'young@lg.com']}
>>> 
```

**Comment by baigreen** [comment]
Nice work. Thank you.
