### ISSUE TITLE
if a domain not registered, can i get the include_raw_whois_text?

### ISSUE THREAD

**Issue by baigreen** [DannyCork/python-whois#261]
now it returns None.
However, some domains are available to register, others are reserved.
The info sometimes showed at the whois info.

**Comment by maarten-boot** [comment]
i have currently only 'sz560.com.cn' as a special case, see below

can you give me a example of a reserved domain i can test with 

in case of a exception d does not exist from "d = whois.query()" so i cannot use that to get the raw output, 
i would have to capture the raw output using a new function call like: whois.show_last_raw_output()

```
python3
Python 3.11.1 (main, Jan  6 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
>>> d = whois.query("sz560.com.cn", verbose = True, include_raw_whois_text=True)
['sz560', 'com', 'cn']
we have cn
cn ['sz560', 'com', 'cn']
line count < 5:: cn sz560.com.cn [Querying whois.cnnic.cn]
[whois.cnnic.cn]
No matching record.

try again with ['com', 'cn'], 2, 2
line count < 5:: cn com.cn [Querying whois.cnnic.cn]
[whois.cnnic.cn]
the Domain Name you apply can not be registered online. Please consult your Domain Name registrar

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mboot/.local/lib/python3.11/site-packages/whois/__init__.py", line 256, in query
    data = do_parse(
           ^^^^^^^^^
  File "/home/mboot/.local/lib/python3.11/site-packages/whois/_2_parse.py", line 224, in do_parse
    return handleShortResponse(tld, dl, whois_str, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mboot/.local/lib/python3.11/site-packages/whois/_2_parse.py", line 132, in handleShortResponse
    raise FailedParsingWhoisOutput(whois_str)
whois.exceptions.FailedParsingWhoisOutput: [Querying whois.cnnic.cn]
[whois.cnnic.cn]
the Domain Name you apply can not be registered online. Please consult your Domain Name registrar

>>> print(d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'd' is not defined. Did you mean: 'id'?
>>> 
```

**Comment by baigreen** [comment]
123.xyz is reserved.
the return is None.
Need a way to get the whois_raw_output.

`Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
>>> d = whois.query("123.xyz", verbose = True, include_raw_whois_text=True)
['123', 'xyz']
we have xyz
xyz ['123', 'xyz']
using _server hint whois.centralnic.com for tld: xyz
>>> d`

**Comment by maarten-boot** [comment]
ok i see this is actually a error in the code "No matching record means the domain doesn not exist and the library should not look further in this case as com.cn should be known as a top level domain 
in any case 
the new whois.get_last_raw_whois_data() wll give you some info (available in the next version)

see the print(whois.get_last_raw_whois_data()) below although i will change that to also show all tries

```
python-whois]$ python3

Python 3.11.1 (main, Jan  6 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import whois

>>> d = whois.query(domain="sz560.com.cn", verbose=True)
['sz560', 'com', 'cn']
we have cn
cn ['sz560', 'com', 'cn']
force = False
['whois', 'sz560.com.cn']
[Querying whois.cnnic.cn]
[whois.cnnic.cn]
No matching record.

line count < 5:: cn sz560.com.cn [Querying whois.cnnic.cn]
[whois.cnnic.cn]
No matching record.

try again with ['com', 'cn'], 2, 2
force = False
['whois', 'com.cn']
[Querying whois.cnnic.cn]
[whois.cnnic.cn]
the Domain Name you apply can not be registered online. Please consult your Domain Name registrar

line count < 5:: cn com.cn [Querying whois.cnnic.cn]
[whois.cnnic.cn]
the Domain Name you apply can not be registered online. Please consult your Domain Name registrar

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mboot/DEV/00-github.com/mboot/python-whois/whois/__init__.py", line 270, in query
    data = do_parse(
           ^^^^^^^^^
  File "/home/mboot/DEV/00-github.com/mboot/python-whois/whois/_2_parse.py", line 227, in do_parse
    return handleShortResponse(tld, dl, whois_str, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mboot/DEV/00-github.com/mboot/python-whois/whois/_2_parse.py", line 135, in handleShortResponse
    raise FailedParsingWhoisOutput(whois_str)
whois.exceptions.FailedParsingWhoisOutput: [Querying whois.cnnic.cn]
[whois.cnnic.cn]
the Domain Name you apply can not be registered online. Please consult your Domain Name registrar

>>> print(whois.get_last_raw_whois_data())
{'RawData': '[Querying whois.cnnic.cn]\n[whois.cnnic.cn]\nthe Domain Name you apply can not be registered online. Please consult your Domain Name registrar\n', 'Domain': 'sz560.com.cn'}
>>> 

```

**Comment by maarten-boot** [comment]
with all tries:

```
python3
Python 3.11.1 (main, Jan  6 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
>>> d = whois.query(domain="sz560.com.cn", verbose=True)
['sz560', 'com', 'cn']
we have cn
cn ['sz560', 'com', 'cn']
force = False
['whois', 'sz560.com.cn']
[Querying whois.cnnic.cn]
[whois.cnnic.cn]
No matching record.

line count < 5:: cn sz560.com.cn [Querying whois.cnnic.cn]
[whois.cnnic.cn]
No matching record.

try again with ['com', 'cn'], 2, 2
force = False
['whois', 'com.cn']
[Querying whois.cnnic.cn]
[whois.cnnic.cn]
the Domain Name you apply can not be registered online. Please consult your Domain Name registrar

line count < 5:: cn com.cn [Querying whois.cnnic.cn]
[whois.cnnic.cn]
the Domain Name you apply can not be registered online. Please consult your Domain Name registrar

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mboot/DEV/00-github.com/mboot/python-whois/whois/__init__.py", line 273, in query
    data = do_parse(
           ^^^^^^^^^
  File "/home/mboot/DEV/00-github.com/mboot/python-whois/whois/_2_parse.py", line 227, in do_parse
    return handleShortResponse(tld, dl, whois_str, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mboot/DEV/00-github.com/mboot/python-whois/whois/_2_parse.py", line 135, in handleShortResponse
    raise FailedParsingWhoisOutput(whois_str)
whois.exceptions.FailedParsingWhoisOutput: [Querying whois.cnnic.cn]
[whois.cnnic.cn]
the Domain Name you apply can not be registered online. Please consult your Domain Name registrar

>>> print(whois.get_last_raw_whois_data())
{'Try': [{'Domain': 'sz560.com.cn', 'rawData': '[Querying whois.cnnic.cn]\n[whois.cnnic.cn]\nNo matching record.\n', 'server': None}, {'Domain': 'com.cn', 'rawData': '[Querying whois.cnnic.cn]\n[whois.cnnic.cn]\nthe Domain Name you apply can not be registered online. Please consult your Domain Name registrar\n', 'server': None}]}
>>> 

```

**Comment by maarten-boot** [comment]
is now available in the latest code (but not yet in a newer version)

**Comment by maarten-boot** [comment]
```
python3

Python 3.11.1 (main, Jan  6 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import whois

>>> d = whois.query(verbose=True, domain="123.xyz")

['123', 'xyz']
we have xyz
filterTldToSupportedPattern returns tld: xyz
xyz ['123', 'xyz']
using _server hint whois.centralnic.com for tld: xyz
force = False
['whois', '123.xyz', '-h', 'whois.centralnic.com']
[Querying whois.centralnic.com]
[whois.centralnic.com]
The queried object does not exist: previous registration D76468204-CNIC was purged on 2018-09-12T15:32:53.0Z (DOMAIN NOT FOUND)

>>> Last update of WHOIS database: 2023-01-30T13:59:23.0Z <<<

For more information on Whois status codes, please visit https://icann.org/epp

>>> IMPORTANT INFORMATION ABOUT THE DEPLOYMENT OF RDAP: please visit
https://www.centralnic.com/support/rdap <<<

The Whois and RDAP services are provided by CentralNic, and contain
information pertaining to Internet domain names registered by our
our customers. By using this service you are agreeing (1) not to use any
information presented here for any purpose other than determining
ownership of domain names, (2) not to store or reproduce this data in
any way, (3) not to use any high-volume, automated, electronic processes
to obtain data from this service. Abuse of this service is monitored and
actions in contravention of these terms will result in being permanently
blacklisted. All data is (c) CentralNic Ltd (https://www.centralnic.com)

Access to the Whois and RDAP services is rate limited. For more
information, visit https://registrar-console.centralnic.com/pub/whois_guidance.

>>> print(d.__dict__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute '__dict__'. Did you mean: '__dir__'?


>>> print(whois.get_last_raw_whois_data())
{'Try': [{'Domain': '123.xyz', 'rawData': '[Querying whois.centralnic.com]\n[whois.centralnic.com]\nThe queried object does not exist: previous registration D76468204-CNIC was purged on 2018-09-12T15:32:53.0Z (DOMAIN NOT FOUND)\r\n\r\n>>> Last update of WHOIS database: 2023-01-30T13:59:23.0Z <<<\r\n\r\nFor more information on Whois status codes, please visit https://icann.org/epp\r\n\r\n>>> IMPORTANT INFORMATION ABOUT THE DEPLOYMENT OF RDAP: please visit\r\nhttps://www.centralnic.com/support/rdap <<<\r\n\r\nThe Whois and RDAP services are provided by CentralNic, and contain\r\ninformation pertaining to Internet domain names registered by our\r\nour customers. By using this service you are agreeing (1) not to use any\r\ninformation presented here for any purpose other than determining\r\nownership of domain names, (2) not to store or reproduce this data in\r\nany way, (3) not to use any high-volume, automated, electronic processes\r\nto obtain data from this service. Abuse of this service is monitored and\r\nactions in contravention of these terms will result in being permanently\r\nblacklisted. All data is (c) CentralNic Ltd (https://www.centralnic.com)\r\n\r\nAccess to the Whois and RDAP services is rate limited. For more\r\ninformation, visit https://registrar-console.centralnic.com/pub/whois_guidance.\r\n', 'server': 'whois.centralnic.com'}]}
>>> 

```

**Comment by baigreen** [comment]
Thank you. sir.

**Comment by baigreen** [comment]
To avoid the dict getting bigger and bigger, I reset  LastWhois right now .
Thanks a lot.

```
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from python_whois import whois
>>> whois.query("123.xyz")
we have xyz
>>> whois.query("007.xyz")
we have xyz
>>> print(whois.get_last_raw_whois_data())
{'Try': [{'Domain': '123.xyz', 'rawData': 'The queried object does not exist: previous registration D76468204-CNIC was purged on 2018-09-12T15:32:53.0Z (DOMAIN NOT FOUND)\n\n>>> Last update of WHOIS database: 2023-01-31T08:46:28.0Z <<<\n\nFor more information on Whois status codes, please visit https://icann.org/epp\n\n>>> IMPORTANT INFORMATION ABOUT THE DEPLOYMENT OF RDAP: please visit\nhttps://www.centralnic.com/support/rdap <<<\n\nThe Whois and RDAP services are provided by CentralNic, and contain\ninformation pertaining to Internet domain names registered by our\nour customers. By using this service you are agreeing (1) not to use any\ninformation presented here for any purpose other than determining\nownership of domain names, (2) not to store or reproduce this data in\nany way, (3) not to use any high-volume, automated, electronic processes\nto obtain data from this service. Abuse of this service is monitored and\nactions in contravention of these terms will result in being permanently\nblacklisted. All data is (c) CentralNic Ltd (https://www.centralnic.com)\n\nAccess to the Whois and RDAP services is rate limited. For more\ninformation, visit https://registrar-console.centralnic.com/pub/whois_guidance.\n', 'server': 'whois.nic.xyz'}, {'Domain': '007.xyz', 'rawData': 'The queried object does not exist: previous registration D182914434-CNIC was purged on 2021-06-21T01:02:35.0Z (DOMAIN NOT FOUND)\n\n>>> Last update of WHOIS database: 2023-01-31T08:44:46.0Z <<<\n\nFor more information on Whois status codes, please visit https://icann.org/epp\n\n>>> IMPORTANT INFORMATION ABOUT THE DEPLOYMENT OF RDAP: please visit\nhttps://www.centralnic.com/support/rdap <<<\n\nThe Whois and RDAP services are provided by CentralNic, and contain\ninformation pertaining to Internet domain names registered by our\nour customers. By using this service you are agreeing (1) not to use any\ninformation presented here for any purpose other than determining\nownership of domain names, (2) not to store or reproduce this data in\nany way, (3) not to use any high-volume, automated, electronic processes\nto obtain data from this service. Abuse of this service is monitored and\nactions in contravention of these terms will result in being permanently\nblacklisted. All data is (c) CentralNic Ltd (https://www.centralnic.com)\n\nAccess to the Whois and RDAP services is rate limited. For more\ninformation, visit https://registrar-console.centralnic.com/pub/whois_guidance.\n', 'server': 'whois.nic.xyz'}]}
>>> whois.LastWhois = {"Try":[]}
>>> whois.query("007.xyz")
we have xyz
>>> print(whois.get_last_raw_whois_data())
{'Try': [{'Domain': '007.xyz', 'rawData': 'The queried object does not exist: previous registration D182914434-CNIC was purged on 2021-06-21T01:02:35.0Z (DOMAIN NOT FOUND)\n\n>>> Last update of WHOIS database: 2023-01-31T08:44:46.0Z <<<\n\nFor more information on Whois status codes, please visit https://icann.org/epp\n\n>>> IMPORTANT INFORMATION ABOUT THE DEPLOYMENT OF RDAP: please visit\nhttps://www.centralnic.com/support/rdap <<<\n\nThe Whois and RDAP services are provided by CentralNic, and contain\ninformation pertaining to Internet domain names registered by our\nour customers. By using this service you are agreeing (1) not to use any\ninformation presented here for any purpose other than determining\nownership of domain names, (2) not to store or reproduce this data in\nany way, (3) not to use any high-volume, automated, electronic processes\nto obtain data from this service. Abuse of this service is monitored and\nactions in contravention of these terms will result in being permanently\nblacklisted. All data is (c) CentralNic Ltd (https://www.centralnic.com)\n\nAccess to the Whois and RDAP services is rate limited. For more\ninformation, visit https://registrar-console.centralnic.com/pub/whois_guidance.\n', 'server': 'whois.nic.xyz'}]}
>>> 
```

**Comment by maarten-boot** [comment]
yes , that is a nasty oversight of me, i am testing a fix now:
on entering query the LastWhois will be reset to a empty list

**Comment by maarten-boot** [comment]
fixed in latest code
