### ISSUE TITLE
Identity Digital DPML Brand Protection. whois error

### ISSUE THREAD

**Issue by baigreen** [DannyCork/python-whois#264]
```
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from python_whois import whois
>>> d = whois.query("gpt.domains",verbose = True, include_raw_whois_text=True)
['gpt', 'domains']
we have domains
filterTldToSupportedPattern returns tld: domains
domains ['gpt', 'domains']
using _server hint whois.donuts.co for tld: domains
force = False
['whois', 'gpt.domains', '-h', 'whois.donuts.co']
The registration of this domain is restricted, as it is protected by the Identity Digital DPML Brand Protection policy. Additional information can be found at https://www.identity.digital/what-we-do/brand-protection.
>>> Last update of WHOIS database: 2023-02-01T02:49:24Z <<<

Terms of Use: Identity Digital Inc. provides this Whois service for information purposes, and to assist persons in obtaining information about or related to a domain name registration record. Identity Digital does not guarantee its accuracy. Users accessing the Identity Digital Whois service agree to use the data only for lawful purposes, and under no circumstances may this data be used to: a) allow, enable, or otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited, commercial advertising or solicitations to entities other than the registrar's own existing customers and b) enable high volume, automated, electronic processes that send queries or data to the systems of Identity Digital or any ICANN-accredited registrar, except as reasonably necessary to register domain names or modify existing registrations. When using the Identity Digital Whois service, please consider the following: The Whois service is not a replacement for standard EPP commands to the SRS service. Whois is not considered authoritative for registered domain objects. The Whois service may be scheduled for downtime during production or OT&E maintenance periods. Queries to the Whois services are throttled. If too many queries are received from a single IP address within a specified time, the service will begin to reject further queries for a period of time to prevent disruption of Whois service access. Abuse of the Whois system through data mining is mitigated by detecting and limiting bulk query access from single sources. Where applicable, the presence of a [Non-Public Data] tag indicates that such data is not made publicly available due to applicable data privacy laws or requirements. Should you wish to contact the registrant, please refer to the Whois records available through the registrar URL listed above. Access to non-public data may be provided, upon request, where it can be reasonably confirmed that the requester holds a specific legitimate interest and a 
proper legal basis for accessing the withheld data. Access to this data can be requested by submitting a request via the form found at https://www.identity.digital/about/policies/whois-layered-access/ Identity Digital Inc. reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy.

line count < 5:: domains gpt.domains The registration of this domain is restricted, as it is protected by the Identity Digital DPML Brand Protection policy. Additional information can be found at https://www.identity.digital/what-we-do/brand-protection.
>>> Last update of WHOIS database: 2023-02-01T02:49:24Z <<<

proper legal basis for accessing the withheld data. Access to this data can be requested by submitting a request via the form found at https://www.identity.digital/about/policies/whois-layered-access/ Identity Digital Inc. reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/code/whois/python_whois/whois/__init__.py", line 279, in query
    data = do_parse(
  File "/home/ubuntu/code/whois/python_whois/whois/_2_parse.py", line 227, in do_parse
    return handleShortResponse(tld, dl, whois_str, verbose)
  File "/home/ubuntu/code/whois/python_whois/whois/_2_parse.py", line 135, in handleShortResponse
    raise FailedParsingWhoisOutput(whois_str)
python_whois.whois.exceptions.FailedParsingWhoisOutput: The registration of this domain is restricted, as it is protected by the Identity Digital DPML Brand Protection policy. Additional information can be found at https://www.identity.digital/what-we-do/brand-protection.
>>> Last update of WHOIS database: 2023-02-01T02:49:24Z <<<

proper legal basis for accessing the withheld data. Access to this data can be requested by submitting a request via the form found at https://www.identity.digital/about/policies/whois-layered-access/ Identity Digital Inc. reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy.

>>> 
```

**Comment by maarten-boot** [comment]
You expect a None return ?
As the domain is not registered ?

**Comment by maarten-boot** [comment]
i have added "The registration of this domain is restricted" as a valid reason for None
