### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'whois': 'whois'

### ISSUE THREAD

**Issue by hu0514** [DannyCork/python-whois#270]
import whois

    s = whois.query('baidu.com')

    print(s.__dict__)

Traceback (most recent call last):
  File "/data/leisu/leisu_api/apps/app_api/view/intelligence.py", line 1027, in <module>
    s = whois.query('baidu.com')
  File "/data/leisu/leisu_env/lib/python3.7/site-packages/whois/__init__.py", line 270, in query
    verbose=verbose,
  File "/data/leisu/leisu_env/lib/python3.7/site-packages/whois/_1_query.py", line 74, in do_query
    verbose=verbose,
  File "/data/leisu/leisu_env/lib/python3.7/site-packages/whois/_1_query.py", line 175, in _do_whois_query
    env={"LANG": "en"} if dl[-1] in ".jp" else None,
  File "/data/local/python3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data/local/python3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'whois': 'whois'

**Comment by maarten-boot** [comment]
i have updated the readme with dependency info on the cli whois command

**Comment by maarten-boot** [comment]
i expect that this issue can be closed
