### ISSUE TITLE
Error: file not found

### ISSUE THREAD

**Issue by JScharloo** [DannyCork/python-whois#34]
import whois
info = whois.query("google.com")
print(info)

Results in the following traceback:

```
Traceback (most recent call last):
  File "/home/mastermind/Projects/DomainInformation/getinfo.py", line 13, in <module>
    info = whois.query(domain)
  File "/usr/local/lib/python3.5/dist-packages/whois/__init__.py", line 50, in query
    pd = do_parse(do_query(d, force, cache_file, slow_down, ignore_returncode), tld)
  File "/usr/local/lib/python3.5/dist-packages/whois/_1_query.py", line 44, in do_query
    _do_whois_query(dl, ignore_returncode),
  File "/usr/local/lib/python3.5/dist-packages/whois/_1_query.py", line 58, in _do_whois_query
    p = subprocess.Popen(['whois', '.'.join(dl)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'whois'
```
(whois package installed through pycharm/pip)

**Comment by JScharloo** [comment]
Stupid little mistake. The Linux whois package wasn't installed on my fresh dev machine. Mea culpa!

**Comment by azzamsa** [comment]
Oh, no. 

Using new machine. I just wanna make new issue regarding "FileNotFoundError: [Errno 2] No such file or directory: 'whois': 'whois'" error. Turn out I get this issue recommendation.

To prevent something like this again, We need to put `install whois package from your distribution` phrase in readme.
