### ISSUE TITLE
basic query function error

### ISSUE THREAD

**Issue by ActuallyDaneel** [DannyCork/python-whois#94]
basic test
```
import whois
site = whois.query('google.com')
print(site.__dict__)
```

error:
```
Traceback (most recent call last):
  File "C:/Users/backup/PycharmProjects/beedle testing ground/main.py", line 3, in <module>
    site = whois.query('google.com')
  File "C:\Users\backup\PycharmProjects\beedle testing ground\venv\lib\site-packages\whois\__init__.py", line 63, in query
    pd = do_parse(do_query(d, force, cache_file, slow_down, ignore_returncode), tld)
  File "C:\Users\backup\PycharmProjects\beedle testing ground\venv\lib\site-packages\whois\_1_query.py", line 46, in do_query
    _do_whois_query(dl, ignore_returncode),
  File "C:\Users\backup\PycharmProjects\beedle testing ground\venv\lib\site-packages\whois\_1_query.py", line 60, in _do_whois_query
    p = subprocess.Popen(['whois', '.'.join(dl)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "C:\Users\backup\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\backup\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

**Comment by fhightower** [comment]
There is more discussion about this issue in #123 .
